### ISSUE TITLE
make xdebug key editable

### ISSUE THREAD

**Issue by kampfq** [kampfq/SafariXDebugToggle#2]

**Comment by gmgarrison** [comment]
For easy reference, the current IDE key is XDEBUG_SESSION. (Please correct if I'm wrong.) It would probably be helpful to indicate it in the "installation" if it's not editable.

**Comment by kampfq** [comment]
The IDE Key is XDEBUG_ECLIPSE, the name of the cookie is XDEBUG_SESSION :)
